#service yml

#AKS services file

apiVersion: v1
kind: Service
metadata:
    name: inventoryMgt-BE
spec:
    type: ClusterIP
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    selector:
        app: inventoryMgt-BE